'use client';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SessionProvider } from 'next-auth/react'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import  "./app.scss";
const inter = Inter({ subsets: ['latin'] })
const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { session, ...params },
}: {
  children: React.ReactNode,
  params: any
}) {
  return (
    <html lang="en">
      <body style={{position:"absolute",backgroundBlendMode:"30",top:0,bottom:0,right:0,left:0,"backgroundImage":`url("scattered-forcefields.svg")`,"backgroundRepeat":"no-repeat","backgroundSize":"cover"}}>
        <SessionProvider session={session}>
          <AppRouterCacheProvider>
            {children}
          </AppRouterCacheProvider>
        </SessionProvider>
      </body>
    </html>

  )
}
